# Site settings
title: Jobs at GitBook
email: contact+jobs@gitbook.com
description:  All open positions to work at GitBook.com
owner: GitBook
baseurl: "/jobs.gitbook.com/"
url: "http://gitbookio.github.io"

# Build settings
markdown: kramdown
