# Site settings
title: Jobs at GitBook
email: contact+jobs@gitbook.com
description:  All open positions to work at GitBook.com
owner: GitBook
baseurl: ""
url: "http://jobs.gitbook.com"

# Build settings
markdown: kramdown
